name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: P3 - NB-LR
      id: p3-nb-lr
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: 'pip install pytest torch '
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        P3-NB-LR_RESULTS: "${{steps.p3-nb-lr.outputs.result}}"
      with:
        runners: p3-nb-lr
